# Generated by Django 5.0.7 on 2024-08-12 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_remove_ad_event_dates_remove_ad_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
