# Generated by Django 5.1 on 2024-08-12 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_ad_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ads.ad'),
        ),
    ]
